version: '3.8'

services:
  app:
    build: .
    ports:
      - "9999:9999"
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=password
      - DB_NAME=pdfdb
    depends_on:
      - db
    volumes:
      - ./:/app
    working_dir: /app

  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=pdfdb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - "9832:9832"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  postgres_data: